---
apiVersion: v1
kind: Namespace
metadata:
  name: plex

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex

spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
      gen: "1"

  template:
    metadata:
      labels:
        app: plex
        gen: "1"

    spec:
      hostNetwork: yes
      containers:
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always

          env:
            - name: PUID
              value: "4402"
            - name: PGID
              value: "4402"
            - name: VERSION
              value: "latest"
#            - name: PLEX_CLAIM
#              value: "..."

          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-media
              mountPath: /media
              readOnly: yes

      volumes:
        - name: plex-media
          hostPath:
            path: /dat/media

        - name: plex-config
          hostPath:
            path: /dat/plex/etc
